import { Inter } from 'next/font/google'
import './globals.css'

import UserInfo from './components/user-info';
import SessionProvider from './components/x-session-provider';
import SideNav from './components/side-nav';
import { auth } from "@/auth"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ 
  children,
 }: { 
  children: React.ReactNode
}) {
  const session = await auth();

  return (
    <html lang="en">
      <body className='bg-gray-100'>
        {/* <SessionProvider session={session}> */}
        <SideNav />
          
          <main className="mx-auto max-w-5xl flex gap-p">
          <UserInfo session={session} />
          {children}
          </main>
        {/* </SessionProvider> */}
        </body>
    </html>
  )
}
